### ISSUE TITLE
hipchat support, feature request

### ISSUE THREAD

**Issue by MatzeJoerling** [guidone/node-red-contrib-chatbot#115]
the bot framework looks very sophisticated. i would like to use it with our hipchat installation.
any plans / ideas to implement hipchat as another chat service?

regards

**Comment by guidone** [comment]
Thanks for the feedback @MatzeJoerling , I'll look into to, as far as I know HipChat does not support advanced feature like buttons, etc so it will be sufficient to implement messages and upload/download of binaries.

I'll add to the roadmap, since I'm not a regular user of HipChat I'll need someone to help testing, are you in?

**Comment by MatzeJoerling** [comment]
looks like atlassian today launched "Stride", what looks like the successor of Hipchat?? 
I certainly will run hipchat für a longer time because i run the onprem solution.
For sure i will test all what you need.

**Comment by guidone** [comment]
@MatzeJoerling I guess hipchat is dead in favour of Stride.

I'm working on the support for Slack and to do this I'm developing a kind of framework in order to make the support for chat platform easier.
I've requested an early access to Stride, meanwhile I'll add to the roadmap.

https://github.com/guidone/node-red-contrib-chatbot/wiki/Roadmap
