### ISSUE TITLE
Telegram Live Location possible?

### ISSUE THREAD

**Issue by opep** [guidone/node-red-contrib-chatbot#229]
Hello,
I could capture a single location using TELEGRAM IN node, but when trying to capture Telegram Live Location, nothing happens. I don't know if there is other way to do it, if there is something wrong or it is just not possible to do it.
If someone could shed some light I would be very grateful.
Thanks!

**Comment by guidone** [comment]
I’ll check and let you know

Thanks for the feedback

**Comment by guidone** [comment]
@opep apparently is not possible

https://stackoverflow.com/questions/48238445/how-can-i-get-live-location-in-telegram-bot-via-python

it just shares the first location and that's it, no updates. 
Perhaps using a webhook instead of polling (RedBot uses polling) is different, but I wouldn't bet on it

**Comment by opep** [comment]
Ok. Thanks for checking.

**Comment by albydnc** [comment]
@guidone at the link you've posted there's been some updates. Is it now possible to use the Live Location?

**Comment by guidone** [comment]
Let me check
