### ISSUE TITLE
Blumix/Facebook "Unable to get profile info for user..."

### ISSUE THREAD

**Issue by wilpickl1** [guidone/node-red-contrib-chatbot#251]
Hello, I am trying to get a simple RedBot chat running on IBM's Blumix cloud platform. When I send a message to the page in question (I have properly set up everything on Facebook's end and have tested the connection at `{mywebsite}.myblumix.net/redbot/facebook/test`), I receive an error in the Node-RED dashboard saying:

`"Unable to get profile info for user 1726684xXxXxXxXx - (#100) Insufficient permission to access user profile.`

I saw that this issue was raised in late August (Issue #234), and it said to be resolved in RedBot version 0.14.5. Below I've included a snapshot of the "Hello, world" program I am trying to run.

<img width="640" alt="screen shot 2018-10-02 at 2 29 39 pm" src="https://user-images.githubusercontent.com/43617085/46372052-a5bad100-c64f-11e8-9f0d-dc3530f34d31.png">

**Comment by wilpickl1** [comment]
Thank you for replying!
I used Facebook Graph API Explorer to create a Page Access Token that will never expire. Unfortunately, after using this new Page Access Token I still run into the same issue.

**Comment by guidone** [comment]
I think I've found the problem

https://developers.facebook.com/docs/messenger-platform/identity/user-profile/

The new API requires a special permission for fetching the user's "locale", I'll remove it then I'll upgrade  the library in order to make the list of requested fields configurable and use the new 3.1 api

Thanks for the feedback

**Comment by guidone** [comment]
Ok published in `0.15.3`
