### ISSUE TITLE
No debug from Discord In node..

### ISSUE THREAD

**Issue by athphane** [guidone/node-red-contrib-chatbot#294]
Trying to use the Discord nodes. 
This replied to every single message. 
![Capture](https://user-images.githubusercontent.com/13810742/54485478-102c9a00-489b-11e9-9848-46c58d83560d.PNG)

But when I put debug node, it does not reply or show a debug message.
![Capture](https://user-images.githubusercontent.com/13810742/54485492-4702b000-489b-11e9-8b2f-db554c75a0d5.PNG)

What do you think is going on?

**Comment by guidone** [comment]
Yes, if you put a debug node it breaks.
Here's the problem, the DiscordJS api is object oriented, everything is a class, when the code receives a message it gets class and in order to answer to the message must be used a method of this class.

So this message class has to be carried around inside the node-red messsages (the first node receives and store in the node-red message, the last node sends the reply).

The problem is that doing a console.log of this class breaks, it's not serializable into string, most likely there are some circular references in this object and it breaks.
There's nothing I can do on Node-RED side
