### ISSUE TITLE
API.AI node

### ISSUE THREAD

**Issue by ram1505** [guidone/node-red-contrib-chatbot#30]
Hi,
I am trying to use the API.AI node in my chatflow. I've defined my entities and intents on api.ai and am not sure how to use the api.ai chatbot flow.

**Comment by ram1505** [comment]
hi,
any info on this would be much appreciated.

**Comment by toddmedema** [comment]
@guidone I'd also love to see support for this!

**Comment by soundman666** [comment]
I was able to make it work. But I do not really understand how to "navigate" between contexts. I think that because of the "cyclical" nodes "api.ai" context / topic does not change correctly.

![image](https://cloud.githubusercontent.com/assets/11494430/23538144/b9e44456-ffd9-11e6-94eb-bade1fa6100b.png)

**Comment by ram1505** [comment]
I was able to get response from API.AI based on the context that I type in Telegram. However, the fulfilment (end result) that API.AI delivers cannot be captured in chatbot. I'm stuck here.

**Comment by fpsimonee** [comment]
I have the same question about navigating between contexts, it's possible to filter dialogue with output contexts for api ai? How does the api ai node work? Is there any documentation or examples of the use?

**Comment by guidone** [comment]
@fpsimonee I've not been using the api.ai node for a while, I'll work on it and try to improve the documentation and a blog post

**Comment by fpsimonee** [comment]
@guidone Thank you, man.
