### ISSUE TITLE
Problems with sending a heavy file .zip to telegram

### ISSUE THREAD

**Issue by daddvok** [guidone/node-red-contrib-chatbot#453]
My main goal is to send folders to telegram, the only option that I found is to pre-compress the folder into .zip format. By executing `sudo apt-get install zip`, the compression of folders became available with the command `sudo zip -r filename file path`. Compressing the 480MB file, I ended up with a total of 185MB, which isn't much. when i try to send a file to a telegram with node document, i see in debug "Error opening file “file path”". In log i see (pictured) that for some reason the file weighs more than 500 MB. Can you please tell me how i can solve the problem?
![F75E2A98-9E22-44C2-8232-AB3987B0EE94](https://user-images.githubusercontent.com/47695947/102735671-198e4480-4354-11eb-94a0-d31f81111b8a.jpeg)

**Comment by guidone** [comment]
Your server is running out of memory, the problem is that doing this way entire file will be encoded and passed through messages (see heap of of memory), the only way is to upload the file directly in telegram with the API and try to send using the id rather than a buffer (but this is not yet supported by RedBot).

Did you find any workaround?
