### ISSUE TITLE
listen-node does not match

### ISSUE THREAD

**Issue by ploebb** [guidone/node-red-contrib-chatbot#69]
A weird problem: The listen node with two entries "an" and "aus" matches "/heizung an" but not "/heizung aus". I also tried it with "aus[word]".

**Comment by guidone** [comment]
Hi @ploebb, here is the point: the library I'm using try to parse english language and as you can see it chunks the two word "/heizung aus" into a single entity, for this reason in the listen node a token that matches this chunk should be "heizung aus".

I understand that is not very useful for non-english sentence, I'll try a workaround for that, for the moment try with the token "heizung aus".

<img width="362" alt="schermata 2017-05-02 alle 10 02 35" src="https://cloud.githubusercontent.com/assets/502519/25609207/7eb34930-2f1e-11e7-85b4-5bba9ab1fc2f.png">

**Comment by jazzista88** [comment]
Hi guidone i have a question about liaten node.
I need to match a sentence like this:

report New Dashboard 1 in pdf

Where New Dashboard 1 is a name with spaces related to a dashboard of a web service.
I set the listen node in this way:

report -> in ->format

In this way it does not work, but i don't know how to set the sentence since the dashboard names are all different and could be just a word or three as in this case or more. Could you help me ?

**Comment by ploebb** [comment]
Thanks for your help @guidone! Sadly your suggestion is no option for my specific case, but I just used a standard switch node and did the parsing in a function-node myself. 
Nonetheless your answer was very helpful for understanding the listen-node!

**Comment by guidone** [comment]
👍 ok, I'll improve it, thanks for the feedback
