### ISSUE TITLE
rivescript call a flow in async

### ISSUE THREAD

**Issue by francescoagati** [guidone/node-red-contrib-chatbot#78]
can rivescript script call another flow?

**Comment by TotallyInformation** [comment]
I don't think you can do that directly. Though you can call JavaScript functions inside Rivescript. The way I am approaching the issue is to output some text that starts with a keyword - in my case something starting with an underscore - and then using a switch node after the rivescript node to filter off the "commands" so that they don't go out to the external service (Telegram in my case).

Here is an example of a Rivescript with embedded Javascript.

```
! version = 2.0
// https://www.rivescript.com/docs/tutorial#getting-started

! global debug = false

! array lcontrol = on|off|up|down
! array lights = landing|hall|living|tree|loft|all
! array colors = red|blue|green

// --- Control the lights --- //
+ (light|lights) (@lcontrol)
- Which light <star2>?

+ (@lights)
% which light *
- light <star> <botstar>

+ (@lights) [light][s] (@lcontrol)
- light <star1> <star2>

+ (light|lights) (@lights) (@lcontrol)
- _light <star2> <star3>
// --- Control the lights --- //

+ google *
- Google search: <a href='https://google.co.uk/search?q=<star>' target='_blank' title='Search results in new tab'>Click Here</a>

+ (hi|hello)[ *]
- Hello <get firstName>, my name is Pi BOT

// Demonstrates both alternatives and an optional
+ is it (day|night)[?]
* <get daynight> == undefined => I don't know if it is day or night!.
- <get firstName>, It is <get daynight>

+ why did you say that[?]
- I said, `<reply>`, because you said, `<input>`.

+ what[?]
@ why did you say that

+ who said that[?]
- Hi, this is Pi BOT here <get firstNamee>.

+ mytest
- Result: <call>mytest</call>

+ *
- I'm sorry <get firstName>, I didn't understand I'm afraid. Could you please rephrase?


> object mytest javascript
  console.warn('Rivescript JS function called');
  return 'Wow';
< object
```

In this case, sending "mytest" to the bot results in both text output and an entry on the Node-RED log. Note that you do not have access to the Node-RED objects you might expect in a function node.

**Comment by TotallyInformation** [comment]
Just to note that I'm trying to work up a blog post to show people how to use chatbot in a more realistic way than the current tutorials show.
