### ISSUE TITLE
chat context memory and scalability

### ISSUE THREAD

**Issue by francescoagati** [guidone/node-red-contrib-chatbot#80]
i have see that chatcontextstore is sync and in memory. this can be a problem for scalability when there are more node process for the same chatbot.
what do you think about move this to an async store (with fiber for example)  and make it pluggable for use with external stores?

**Comment by guidone** [comment]
Yes soon or later the scalability will be a problem.

I was thinking about something pluggable, in this way anyone can write it own stores (memory, redis, mysql, etc).

Moving every chat context read to an async method will have quite an impact on the code but it's sure we have to deal with asynchronicity.
I know a little about Fiber, I'll look into it

**Comment by francescoagati** [comment]
Or another solution can be simple get and save the state in the flow with some nodes that read and write the state instead of incapsulate the store in the request and response node

**Comment by francescoagati** [comment]
Or make the nodes completely stateless and leave the state manage to the flow

**Comment by francescoagati** [comment]
If the node request are stateless the process of storage manage can be assigned to the flow that is async

**Comment by guidone** [comment]
Ok, up to now the key points are

- connectors for the chat context must be pluggable and not embedded in the transport nodes
- connectors can be async
- we don't want to give away the easy of use of the .chat() method inside function and we don't want to rewrite most of the code in an async way just to grab data that is already included in the message payload from the chat platforms (like chatId, name, etc) 

One of the lessons of Node-RED that I've learnt up to now is to don't load a node with too much functionalities, don't do something in a node that you can do it in two nodes. This makes the flow more "composable".

Since there's already a context node

<img width="633" alt="context-node" src="https://user-images.githubusercontent.com/502519/27229917-b55ce5b0-52ad-11e7-9d76-fe1717558820.png">

We can expand this with a combo box with all available context connectors (default and third party), the node flow will handle the async call like usual (with promises) and will still be possibile to use the plain (sync) chat context.

In order to have the bot stateless the chat context node must be used. If this is not a requirement then it's safe to use the plain sync chat context.

What do you think?

**Comment by francescoagati** [comment]
hi,
i think that the use of context node is a good solution

**Comment by TotallyInformation** [comment]
This should also get you permanent stores for "free" in a future version of Node-RED as I believe that there is a plan to implement permanent pluggable stores for global/flow/context.

**Comment by guidone** [comment]
Closing, added to the roadmap https://github.com/guidone/node-red-contrib-chatbot/wiki/Roadmap
